FROM node:latest

WORKDIR /app

COPY package*.json ./

RUN npm install 

COPY . .

ENV PORT 500

#DEVELOPMENT
CMD ["npx", "nodemon", "src/index.ts"]

# PRODUCTION
#RUN npx tsc
#CMD ["node", "dist/index.js"]