FROM node:latest

WORKDIR /app

COPY package*.json ./

RUN npm install 

COPY . .

EXPOSE 5000

#DEVELOPMENT
CMD ["npx", "nodemon", "src/index.ts"]

# PRODUCTION
#RUN npx tsc
#CMD ["node", "dist/index.js"]